version: "3.8"

services:
  auth-service:
    build: .
    container_name: auth_service
    ports:
      - "50051:50051"
    environment:
      - SERVER_ADDRESS=:50051
      - DB_URL=postgres://user:password@db:5432/authdb
      - PRIVATE_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDV3dJQkFBS0JnR3dVVDNTUDBzUlQ2em8xL2tHa0UwV09QNGkwZSt2YndyYnJqNFhjcElZeFRpWXdpcDVRCmI5SWpsc3JYMFgxaytPdG5tUnA5M3pCakcyS2ZqZzNya3d2eFlXTmdSc1hqNFZKdURJWGhvTWQzT3dLdkthYkgKbGVSREZSRUdDL1JxS3hQUUNmTVdlR0xhSmxUTG9mRTlLeHp6bFF1dmN2c256TEh0TnR0SXdPL0JBZ01CQUFFQwpnWUJaYUdmZWJrZ1dYN0c5SXdObHU5eXhjcDUrY1lmK01uc2VwVG5DckNkeVY0Rmx1RXhEOFJqQUJ1N3NlS0wxCmo3MFh5RWp3a0dZOCtnK2lnNG1aWEdMMHIzWFh3RUJxYkJBaWFaOWd6SUVJMFJwVHlnSGxYRmh6alZ6c2JONzYKZEMzUkg3M0thQ2lwRzFIaWx2MVo1MWpXc1hvNVZLWUVXb2x0MWFaOXVWeXZuUUpCQUxISnE2YmtCbEN5aGRuLwpqeGdHWGNVdWM4WVdsWUQ0bUdzTnc1QzYvdW1zSHVJNnlXTzZDZ1REZjhLZFJudE1FWW91QzhJQ3FwNlk4MnV3CjM2YS9DSjhDUVFDYm9DQmZFWUpHOURLV2FhQVpGRFdHNEN3cDVPQXZkckhqL2Q1L2xIQlBOaldJS2tiWTFKVFUKb3FQaW1KaXlneE05UFFsbnNDangwQ0lSVkJweTdFdWZBa0VBbFBOc2I0OWRSeUM2aWREVmx3QkdjWndnZlJhUQp2UlFKeHE4cWFNaHlKMTRBSmZPd3BHL0tVd0ZqdWE1QXphNEdoK2xhQ25wbmJpYWcwbG5HbHhJMzZ3SkFCbUZ2ClVsYUdiK0JOUHF0LysrYy9OcE4wWEJkZE5iVDVJQzdsYzNlamp5dmEwQVZqdURvbkMvekxHVnhHVG5OZlU1QncKRlVjOHRvVmhFRExSanNxdll3SkFDTjY0TDBmTWhka0ZocEZpNG9oN24vaUN2NG4zV2Jic1hYRU95Y1pHQ2JtaAphNm9PVEdqbEE0NjhZMDJ4bGVxWC83UCthYkFLanlsb1M3azNtcEZmL0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
      - PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZU1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTUFEQ0JpQUtCZ0d3VVQzU1Awc1JUNnpvMS9rR2tFMFdPUDRpMAplK3Zid3Jicmo0WGNwSVl4VGlZd2lwNVFiOUlqbHNyWDBYMWsrT3RubVJwOTN6QmpHMktmamczcmt3dnhZV05nClJzWGo0Vkp1RElYaG9NZDNPd0t2S2FiSGxlUkRGUkVHQy9ScUt4UFFDZk1XZUdMYUpsVExvZkU5S3h6emxRdXYKY3ZzbnpMSHROdHRJd08vQkFnTUJBQUU9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
