version: "3.8"

services:
  auth-service:
    build: .
    container_name: auth_service
    ports:
      - "50051:50051"
    environment:
      - SERVER_ADDRESS=:50051
      - DB_URL=postgres://user:password@db:5432/authdb
      - PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM4TDFmamdjekYrR0NYDQpmenIrUGhPNHY0RXBaK0dQeVR1dEdOOFdiWVBmbmp0a1dLRlpXcUpyL20xZzBEcHM0N1dEQm5UcDNOc1ZBalpwDQpnYlN3dzY0aHB1QzFWenJrOCtOQ2c4V2dPNWxMS1N5UzRYT0N5dGRXdDg1R0F4Q3BBUmFuWkJscVk5eVdCTHRLDQpOSWJUTDdialBaeWRHOUJMZHZZUDVNNEZncjlUYmRVcWVjZldsRjhheG5adHNHZ09JT2h6VHR2aFVTWnZON2VYDQpaTFRzK2s1SmYySGJ0Q0twbDRHaG9ZWDV0MzRTcEpwQzVUb3Q5K2lkU0hPbWZrTzRwZ2hlTWVTSVVEaHZnUWRaDQpSUVkyS2dtTXZhakpEZTQ0b200K2hqeU1neDFVcS9XSU5zWjJvZ3JRbFIzSzRZWDRvVjBnZEQ1U09La21SRHkyDQp1RG1USVorbEFnTUJBQUVDZ2dFQUQ2ZWc3WU9haHB5T2pTNTZlSjh1NTZkWFpodW15TWljM3QzckR4UCtETFZUDQoxbG1iZ0pJRGpDMkQvcklMMk9EMDN3a1k0dXlWSUJ3SlFwYUFTQ3FGMEVzRmkxTU45VVp4c1Nmczl6MndySzg5DQo3cHZKT1hLZU05cXN2YWZGeVhMQSs1eXprdVZxK3JnNjRXWFp2UjlOY2xMVU5oWCtmN2RPS2MwbkNMcDkvVUZlDQpOeTFNdHBJUHNNUWFDV2l5VFZWUWtDWmtlZTlYWEI5U2FiYmFObFEwUVZsQS9uVC9wTHgvdnZYV1FxQzBjWGVtDQozeTFjdGxEamc1dnoyNmVkR2I1V1dRbHlsQUcxblpDTEs3U01Ncm1XWVhKQ3N6eHUweTRYQnBmYUZISGxmZzg0DQpaaUZqd3FlcFFHQnZ0QksvYXE1Vi9TY1ljeExmY2tIV1hXMFFrMXhnSVFLQmdRRHdZMG5LcFFBYW5TUE53L2Y5DQpYaWl4NWhJSk44cDk5YWRaYTZ4cE9TM01UelI4TEY2c1JHOTZISk5WQUxna2hCRVRldmw3a0IzY1VpVTY5M1VCDQpkOXpjQWNsRTlwMWhUVEVnb2Y0SUxHMWlaUmFHVXlxQkVKejhMNTZneFQzaEsvcHVSWHB1RjhGWU1CTjMvaXFqDQpqNlYzbHRxaFR0cnR1M3VURno4Y0pJcjlvUUtCZ1FESWFCL1lZdU85Y0JnczV2YW1vQkhMRmpuUzBxc0IrNEtMDQpwVnZOd2dmTEl2TzhHWEpqOVRMbWgvdDlFZ0xQTzNPeHFPWStoQ3VBU1Z6V2dtbm0yU2Nzd2hmMmxhZ2k4WHh3DQpqU0hFeEMrR2w5LzV5dnBqajI0Y3loR3hSekw4MjBmT0Y4cnRIZ0FBa1hUQUpUcUtwUmxtaGF2ZDEvT3pYNnhhDQpxWFZkd2QvN2hRS0JnUURWTHJoYVJrbjVVREpZWU5xa2o4UjNRQm51b3RPcE1SbmdhMlRUVENvWmJvU1ZPcVFiDQpFZlhxelR5N3ZZK1FrcTZ5SC9Ud1o3YVRsU1gvVFVVdXNDWGwxbyt2NFNWaERSdnNYTHowY3JIdStNY3BDTWhBDQovWUs3QTJBaUk4bmt6eU9nZDIxRUJUMHFBRGpEeVZ2M0FZVTBzVXZpa2hRRmtLYmVvMWNNbGp2TkFRS0JnQTRYDQpSQ1h5emhDRDBTOVhEZ0NwUUpjRytRblp4aXhkZ3RCTzBDV25mdVRKa0ZtcGNHR1cyLzFaa2xVNDd2bWpOSDlKDQpZT2NFWkFxaEhlWDNSWHIxeWN0YjJsTjhNbFpDcEgxRmJ4cG1zUERGdlBuVFM4ZTBUZ200SzRaTGUwcE1JTUJjDQo2K2ZBTkQvVitsK0lQcFdCQmtndkhlWjdTS2RVRXNwTkgvTjNya2dCQW9HQkFLMDRDYjk0enIxYzNJajV0Q2R4DQpJZVhDYXd2QlVwM3RCT0tQakRGYzVpaDNINHRkWFpMT3psWW45TDF3SGRuM3BIaUlJTFJkVjFIV29aR2lNQTA2DQp2bXBDZ1lJM0UvYzlqRnozbWlzenRLZ2RKdzNsZ3ZKR2RsYmZwcm9EUDBxdW1oYUV2cEVPRTlxWFJ1bXNwMDlxDQpuOXpNOFZtTi8wMGVLbGpKUkVYbnFvc2INCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
      - PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdkM5WDQ0SE14ZmhnbDM4Ni9qNFQNCnVMK0JLV2ZoajhrN3JSamZGbTJEMzU0N1pGaWhXVnFpYS81dFlOQTZiT08xZ3daMDZkemJGUUkyYVlHMHNNT3UNCklhYmd0VmM2NVBQalFvUEZvRHVaU3lrc2t1Rnpnc3JYVnJmT1JnTVFxUUVXcDJRWmFtUGNsZ1M3U2pTRzB5KzINCjR6MmNuUnZRUzNiMkQrVE9CWUsvVTIzVktubkgxcFJmR3NaMmJiQm9EaURvYzA3YjRWRW1iemUzbDJTMDdQcE8NClNYOWgyN1FpcVplQm9hR0YrYmQrRXFTYVF1VTZMZmZvblVoenBuNUR1S1lJWGpIa2lGQTRiNEVIV1VVR05pb0oNCmpMMm95UTN1T0tKdVBvWThqSU1kVkt2MWlEYkdkcUlLMEpVZHl1R0YrS0ZkSUhRK1VqaXBKa1E4dHJnNWt5R2YNCnBRSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 10
